site_name: Rudaux Docs
repo_url: https://github.com/samhinshaw/rudaux/
edit_uri: ''
site_description: Documentation for rudaux, a python module for administering a course using JupyterHub, Canvas, and nbgrader.
site_author: Sam Hinshaw
copyright: '&copy; 2018 Sam Hinshaw, BSD-3'
nav:
  - Home: index.md
  - CLI: cli.md
  - Classes: classes.md
  - Configuration: config.md
  - Examples:
      - Functions: examples/functions.md
      - Objects: examples/objects.md
theme:
  name: yeti
  custom_dir: theme
markdown_extensions:
  - codehilite
