site_name: Rudaux
nav:
  - Home: index.md
  - CLI: cli.md
  - Modules: modules.md
  - Configuration: config.md
  - Examples:
      - Functions: examples/functions.md
      - Objects: examples/objects.md
theme:
  name: yeti
  custom_dir: theme
markdown_extensions:
  - codehilite
